# Generated by Django 3.2.18 on 2023-03-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_ID_Model',
            fields=[
                ('customer_ID', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Customer_ID_Model',
            },
        ),
        migrations.CreateModel(
            name='HeaderField_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField()),
                ('Limit', models.IntegerField(default=100)),
                ('Remaining', models.IntegerField(default=100)),
                ('Reset', models.IntegerField(default=1)),
                ('RetryAt', models.IntegerField(default=0)),
                ('upData', models.DateTimeField(auto_now=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer_id_model')),
            ],
            options={
                'db_table': 'HeaderField_Model',
            },
        ),
    ]
