# Generated by Django 3.2.18 on 2023-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_id_model_headerfield_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GET_Model',
            fields=[
                ('customer_ID', models.TextField(primary_key=True, serialize=False)),
                ('Limit', models.IntegerField(default=100)),
                ('Remaining', models.IntegerField(default=100)),
                ('Reset', models.IntegerField(default=1)),
                ('RetryAt', models.IntegerField(default=0)),
                ('upData', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GET_Model',
            },
        ),
        migrations.CreateModel(
            name='POST_Model',
            fields=[
                ('customer_ID', models.TextField(primary_key=True, serialize=False)),
                ('Limit', models.IntegerField(default=1)),
                ('Remaining', models.IntegerField(default=1)),
                ('Reset', models.IntegerField(default=1)),
                ('RetryAt', models.IntegerField(default=0)),
                ('upData', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'POST_Model',
            },
        ),
        migrations.RemoveField(
            model_name='headerfield_model',
            name='ID',
        ),
        migrations.DeleteModel(
            name='Customer_ID_Model',
        ),
        migrations.DeleteModel(
            name='HeaderField_Model',
        ),
    ]
