# Generated by Django 3.2.18 on 2023-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230322_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_model',
            name='path',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='post_model',
            name='path',
            field=models.TextField(default='n/a'),
        ),
    ]
